apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../all_clusters # adds overlays for all clusters to sandbox clusters
- ../application_clusters # adds overlays for application clusters to sandbox clusters

commonAnnotations:
  environment: sandbox
