apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add configurations for management cluster
- ../all_clusters # adds overlays for all clusters to management

- ../../bases/gitops_managed_clusters/ # adds management cluster apps
- ../../bases/tekton/

commonAnnotations:
  environment: management-clusters
