apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add configurations for management cluster
- ../all_clusters # adds all cluster apps
- ../../bases/management_clusters # adds management cluster apps

commonAnnotations:
  environment: management
