apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../all_clusters # adds overlays for all clusters to production clusters
- ../application_clusters # adds overlays for application clusters to production clusters

commonAnnotations:
  environment: production
